### ISSUE TITLE
CI for vcert-java

### ISSUE THREAD

**Issue by pegerto** [Venafi/vcert-java#1]
Hello @tr1ck3r

Thank you very much for creating this repository, we would initially use Travis for CI, but we have observed you build the ve-cert with Jenkins, happy to create a Jenkins file as well on this project but it will require your input

Please feel free to share any input with this ticket.

**Comment by tr1ck3r** [comment]
You're welcome @pegerto.  Yes, we use Jenkins for all of our other open source integrations and will be happy to provide input in that area when you're ready.
