### ISSUE TITLE
405 Method Not Allowed - when calling readZoneConfiguration with 0.9.1 and 0.9.2

### ISSUE THREAD

**Issue by kai83** [Venafi/vcert-java#115]
I am running the following code based on your documentation.

When using the vcert version 0.9.0, then everything works fine.
Using 0.9.1 and 0.9.2 is causing the following error:

```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	at com.google.gson.Gson.fromJson(Gson.java:826)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:747)
	at com.venafi.vcert.sdk.VCertException.fromFeignException(VCertException.java:44)
	at com.venafi.vcert.sdk.VCertClient.readZoneConfiguration(VCertClient.java:172)
```

	static String user = "username";
	static String password = "password";
	static String clientID = "cliendiD";
	static String url = "https://sserverurl";
	static String policy = "Venafi Client\\Client1";

	final Authentication auth = Authentication.builder()
		        .user(user)
		        .password(password)
		        .clientId(clientID)
		        .build();

		final Config config = Config.builder()
		        .connectorType(ConnectorType.TPP_TOKEN)
		        .baseUrl(url)
		        .build();
		        
		final VCertTknClient client = new VCertTknClient(config);

		client.getAccessToken(auth);

		client.readZoneConfiguration(policy);
		`
Can you please let me know if something, on how to retrieve the ZoneConfiguration, has been changed?

**Comment by kai83** [comment]
I made some further tests:
If using the VCertTknClient against a on Premise (TPP) System, then I receive the mentioned 405 error.
If using the Cloud connector against Venafi as a Service with the following code, then all works fine:

`final Authentication auth = Authentication.builder()
	.apiKey("xxxxxxxxxxxxxx")
	.clientId(clientID)
	.build();

final Config config = Config.builder()
	.connectorType(ConnectorType.CLOUD)
	.build();

final VCertClient client = new VCertClient(config);
	client.authenticate(auth);
	ZoneConfiguration zone = client.readZoneConfiguration(policy);

System.out.println(zone);`

**Comment by tr1ck3r** [comment]
@kai83 I have confirmed there is an issue in v0.9.0 and higher that has to do with handling of the URL.  The 405 error is happening because the method URL is missing the `/vedsdk` portion but when you include the `/vedsdk` portion in the base URL the authentication portion fails because it uses `/vedauth`.  The `/vedsdk` portion is supposed to be optional (i.e., we automatically add it if it is not present for non-auth calls, and automatically replace it with `/vedauth` if it is present).  I've asked @marcos-albornoz to investigate getting it fixed.

**Comment by kai83** [comment]
Hi @tr1ck3r 
thank for your feedback and quick testing.
In the meanwhile I found another issue, let me know if this is caused by the same or if you want me to open another ticket.

Calling client.ping() on venafi as a service (ConnectorType.CLOUD) is causing a 404 (so I guess URL issue as well).

**Comment by kai83** [comment]
@marcos-albornoz 
thank you for your quick fix and support.
I modified my code to use the authentication through the constructor.
It helps to reduce code, Thank you
