### ISSUE TITLE
Many VCertClient methods rethrow a useless "unexpected exception" error message

### ISSUE THREAD

**Issue by FooBarWidget** [Venafi/vcert-java#12]
**PROBLEM SUMMARY**
Many VCertClient methods catch Exception, only to throw a generic VCertException with a non-helpful error message "unexpected exception". For example:

~~~java
try {
  return connector.requestCertificate(request, zoneConfiguration);
} catch (FeignException e) {
  throw VCertException.fromFeignException(e);
} catch (Exception e) {
  throw new VCertException("Unexpected exception", e);
}
~~~

As a result, the original exception's message is lost (unless one makes an effort to extract it with `getCause()`). This makes troubleshooting difficult.

I looks like all (or nearly all) of the `connector.something()` methods can only throw VCertException anyway, so I suggest removing the `catch (Exception e)`.

**STEPS TO REPRODUCE**
Request a certificate without a common name set.

**EXPECTED RESULTS**
A VCertException is thrown with a useful error message, like this: "The requested CN does not match any of the allowed CN regular expressions"

**ACTUAL RESULTS**
A VCertException is thrown with a useless error message: "Unexpected exception"

**Comment by tr1ck3r** [comment]
@FooBarWidget would you be interested in contributing this enhancement to the project via a pull request?  I agree with you that improvement is needed in this area but we likely won't be able to get to it ourselves for awhile due to other priorities.
