### ISSUE TITLE
Please publish vcert-java to Maven Central

### ISSUE THREAD

**Issue by FooBarWidget** [Venafi/vcert-java#14]
Vcert-java is not on Maven Central. As a result, I either have to import the entire source code into my project, or I'll have to use it via jitpack.io. However jitpack.io is slow and unreliable.

Please publish vcert-java to Maven Central.

**Comment by marcos-albornoz** [comment]
It's now published in [Maven Central Repository.](https://search.maven.org/search?q=g:io.github.venafi)
