### ISSUE TITLE
Does token authentication apply to Venafi as a Service?

### ISSUE THREAD

**Issue by FooBarWidget** [Venafi/vcert-java#46]
I'm a Venafi partner and I'm developing VCert integration for Jenkins and Gitlab. I was recently asked to switch to token authentication because the old username-password authentication is going to be deprecated.

It appears I need to use VCertTknClient. But VCertTknClient does not support `connectorType == TPP_CLOUD` (Venafi as a Service). Is token authentication applicable to Venafi as a Service? If so, is it supported by vcert-java right now, and am I supposed to use VCertClient or something else?

**Comment by paulternate** [comment]
The update to token authentication is for TPP only. The Venafi as a Service authentication mechanism is still API key.
